### ISSUE TITLE
1.7.10 Latest paperspigot 

### ISSUE THREAD

**Issue by CharlieBru** [AgentManny/LunarClientAPI#1]
Putting the API on the server (1.7.10 latest paperspigot) gives this error:

Kuzni lost connection: Internal Exception: java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/StringUtils

Exact version: https://yivesmirror.com/files/paper/PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar

**Comment by kiingzly** [comment]
same issue, please fix <3

**Comment by TheNickSkater** [comment]
Sorry, but is this going to get fixed? I also have this issue.
